### ISSUE TITLE
Update for 2020 Summer Springboard

### ISSUE THREAD

**Issue by morganjwilliams** [core-skills/11-spatial-data#5]
We'll need to update a few things for the current iteration of the springboard, including:

- [x] The runsheet and timings (both in AEST and AWST), noting Zane's slot will be 12:00-13:30 AWST.
- [x] Clearing out old material which is unused currently.
- [x] Checking the environment file or any outdated or redundant dependencies; update this so it'll run everything smoothly in Binder.
- [x] Adjusting timings for the first session (previously ~1hr, now ~1.5 hr).

**Comment by cericia** [comment]
Updated and cleared old session files in handouts/
